services:
  app:
    image: node:21.1.0
    working_dir: /app
    volumes:
      - .:/app
    command: ["bash", "-c", "npm install && npm run dev"]
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: local-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
